language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t research/research4 -f Dockerfile.dev .

script:
  - docker run -e CI=true research/research4 npm run test

after_success:
  - docker build -t research/research4 .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push research/research4